version: '3.8'
services:
  notes:
    build: .
    ports:
      - "8000:8000"  # Mapeia a porta 8000 do container para a porta 8000 da máquina host
    volumes:
      - .:/var/www/html  # Monta o diretório atual (código local) dentro do container
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql